kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-pvc  # Sets name of PVC
   labels:
      app: postgres
spec:
   storageClassName: manual
   accessModes:
      - ReadWriteMany  # Sets read and write access
   resources:
      requests:
         storage: 5Gi  # Sets volume size
   selector:
      labels: postgres